version: '2'
services:
  haproxy:
    image: haproxy:1.8-alpine
    restart: always
    ports:
      - "6379:6379"
      - "1936:1936"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  master:
    image: redis:4-alpine
    volumes:
      - ./master.cfg:/redis.cfg
    command: redis-server /redis.cfg

  slave:
    image: redis:4-alpine
    volumes:
      - ./slave.cfg:/redis.cfg
    command: redis-server /redis.cfg

  sentinel:
    image: redis:4-alpine
    volumes:
      - ./sentinel.cfg:/redis.cfg
    command: redis-server /redis.cfg --sentinel

  app:
    build: ./app
    image: app
    restart: always
